version: '3.8'

services:
  rebugger-api:
    build: .
    container_name: rebugger-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data        
    restart: always